version: 2
updates:
  - package-ecosystem: npm
    directory: /wretched-whispers-web
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /wretched-whispers-server
    schedule:
      interval: weekly
